### ISSUE TITLE
Sequence number wraparound detection does not work

### ISSUE THREAD

**Issue by JakobStruye** [UBnano-Terasim/thz#5]
The THz MAC receiver detects wrap-around of the 16-bit sequence number as follows:
https://github.com/UN-Lab/thz/blob/4ba792e017f2d081a5d411c9f0a72c9ad7cf0867/model/thz-mac-macro.cc#L1011

First, this check if off-by-one: the sequence number can be at most 65535, so this clause will never be true.
Even when fixed, this wraparound detection will not work if the packet with seqno==65535 was not received properly. Packets with insufficient SINR are dropped before this check is performed.

To fix the above, the ==65535 could be removed, however then the sequence number will fail to filter out a duplicate if a next packet was already received successfully. Perhaps a better fix would be to require some minimum diffference between stored and received sequence numbers, or to have stored sequence numbers expire after some time. I'm not sure what would be the most appropriate fix, and/or if any spec/RFC mandates a specific way of handling this.

**Comment by xcantosr** [comment]
The ==65535 if statement was removed in the latest updates.
